---
type: chart
rootfs:
  - image: samsung_cnct/kibana
    context: kibana
    chart: kibana
    value: image
configs:
  - chart: kibana
    timeout: 600
    retries: 1
    release: kibana
    test:
      values:
    stage:
      values:
prod:
  doDeploy: none
