---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "fullname" . }}-auth
  labels:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
    username: {{ .Values.security.username }}
    password: {{ .Values.security.password }}
